- name: Install haproxy
  apt:
    name:
      - haproxy
      - prometheus-haproxy-exporter

- name: Copy haproxy.conf
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart haproxy

- name: Copy prometheus-haproxy-exporter
  template:
    src: prometheus-haproxy-exporter.j2
    dest: /etc/default/prometheus-haproxy-exporter
  notify: Restart haproxy-exporter

- name: start haproxy
  service:
    name: haproxy
    state: started

- name: start haproxy exporter
  service:
    name: prometheus-haproxy-exporter
    state: started
