- name: Linux user backup
  ansible.builtin.user:
    name: backup
    home: /home/backup
    shell: /bin/bash

- name: Create a 2048-bit SSH key for user backup in ~backup/.ssh/id_rsa
  ansible.builtin.user:
    name: backup
    generate_ssh_key: yes
    ssh_key_bits: 2048

- name: Create a directory /home/backup/restore
  ansible.builtin.file:
    path: /home/backup/restore
    state: directory
    owner: backup
    group: backup
    mode: '0744'

- name: Install duplicity
  apt:
    name: duplicity
    state: present

- name: Uploads /home/backup/.ssh/known_hosts
  template:
    src: known_hosts
    dest: /home/backup/.ssh/known_hosts
    owner: root
    group: root
    mode: '0644'
